config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'items/new'
  root 'sell#index'
  resources :users, only: [:show,:new]
  resources :items, only: [:new,:show , :create , :edit ,:update , :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      
      get "buy"
    end

    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get :done
      end
    end
  end
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  
  # has_many :comments, dependent: :destroy
  # has_many :favorites, dependent: :destroy
  # has_many :todo_lists
  # has_many :user_evaluations
  # has_many :seller_items, foreign_key: "seller_id", class_name: "items"
  # has_many :buyer_items, foreign_key: "buyer_id", class_name: "items"
  # has_one :point
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  # has_one :sns_authentication, dependent: :destroy
  # has_one :sending_destination, dependent: :destroy
  # has_one :credit_card, dependent: :destroy
  has_many :cards
 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :encrypted_password,:nickname, profile_attributes: [:first_name,:family_name,:first_name_kana,:family_name_kana,:birth_year,:birth_month,:birth_day,:postcode,:prefecture,:city,:adress1,:adress2])
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params

  # GET /resource/sign_in
  def new
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.main
  .home-main_header
    .home-main_header_headerInner_mainheader_icon
      = link_to image_tag("logo.png", :size => "185x50")
  .singnup-main
    .singnup-container
      .singnup-container_header 新規会員登録
      .singnup-cantainer_inner
        .inner_content
        .content_box_a
          = link_to “user_path” do
            %button.btn-default.btn-main
              = icon(‘fab’, ‘fa-envelope’)
              %span メールアドレスで登録
        .content_box_b
          = link_to "#" do
            %button.btn-defaoult.btn-sns.btn-facebook
              = icon(‘fab’, ‘facebook-square’)
              %span Facebookで登録
        .content_box_c
          = link_to "#" do
            %button.btn-default.btn-sns.btn-google
              = icon(‘fab’ ,‘google’)
              %span Googleで登録
  .home-main_footer_logo
    = link_to image_tag(“logo.png”,:size => “90x35”),class:“img”
    .home-main_footer_content_box_a
      =link_to “プライバシーポリシー“,"#",class: "a"
    .home-main_footer_content_box_b
      =link_to “FURIMA利用規約“,"#",class: "b"
    .home-main_footer_content_box_c
      =link_to “特定商取引に関する表記“,"#",class: "c"
  %p.p＠FURIMA

app/views/users/show.html.haml
.home-main_header
  .home-main_header_headerInner
    .home-main_header_headerInner_mainHeader
      .home-main_header_headerInner_mainHeader_icon
        = link_to image_tag("logo.png", size: "140x40"),root_path
      .home-main_header_headerInner_mainHeader_searchBox
        %form{ action: '/', method: 'post' }
          %input{ name: 'seach', class: 'toppage-header-top__header-search--search-form',
          placeholder: 'キーワードから探す' }
        .home-main_header_headerInner_mainHeader_search-btn
          = link_to image_tag("icon-search 1.png",class: 'toppage-header-top__header-search--search-btn')
    .home-main_header_headerInner_nav
      %ul.home-main_header_headerInner_nav_listsLeft
        %ui.home-main_header_headerInner_nav_listsLeftlistsLeft_item-first
          =link_to "カテゴリー","#",class: "a"
        %ui.home-main_header_headerInner_nav_listsLeftlistsLeft_item
          =link_to "ブランド","#",class: "a"
.my-nav
  %ul.my-nav_nav
    %il.nav1 
    = link_to "フリマ","#",class:"a"
    %li.nav2 マイページ
.my-main
  .side
    %ul.side-list
      %li.nav3 
        = link_to "プロフィール","#",class:"a"
      %li.nav4
        = link_to "お知らせ","#",class:"a"
      %li.nav4
        = link_to "出品する","#",class:"a"
      %li.nav4
        = link_to "下書き一覧","#",class:"a"
      %li.nav4
        = link_to "出品した商品-出品一覧","#",class:"a"
      %li.nav4
        = link_to "出品した商品-取引中","#",class:"a"
      %li.nav4
        = link_to "出品した商品-売却済み","#",class:"a"
      %li.nav4
        = link_to "購入した商品-取引中","#",class:"a"
      %li.nav4
        = link_to "購入した商品-過去の取引","#",class:"a"
      %li.nav4
        = link_to "ニュース一覧","#",class:"a"
      %li.nav4
        = link_to "評価一覧","#",class:"a"
      %li.nav4
        = link_to "本人情報","#",class:"a"
      %li.nav4
        = link_to "お問い合わせ","#",class:"a"
      %li.nav4
        = link_to "支払い方法",new_card_path,class:"a"
      %li.nav4
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
  .content
    .user
      .userpro
        .myuser
          = link_to "チョコパイ","#",class:"a"
    .sirase
      %ul.mypage
        %li.active お知らせ
        %li.active2 やることリスト
      %ul.come
        %li.comels お知らせはありません
.my-banner
.my-footer
  =render "sell/sell_footer"
.my-btn
  =render "sell/exhibit_ion"