config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'items/new'
  root 'sell#index'
  resources :users, only: [:show,:new]
  resources :items, only: [:new,:show , :create , :edit ,:update , :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    collection do
      
      get "buy"
    end

    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get :done
      end
    end
  end
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :item_images,dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  
  validates :name, presence: true
  validates :text, presence: true
  validates :category_id, presence: true
  validates :price, presence: true, numericality: { greater_than: 300, less_than: 9999999 }
  validates :item_images, length: { minimum: 1, maximum: 4}

  enum condition: { "新品・未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし":3, "やや傷や汚れあり":4, "傷や汚れあり":5, "全体的に状態が悪い":6}
  enum trading_status: { "送料込み（出品者負担)":1, "着払い（購入者負担）":2}
  enum delivery_days: { "1~2日で発送":1, "2〜3日で発送":2, "4〜7日で発送":3}
  enum delivery_area:{
    "北海道":1,"青森県":2,"岩手県":3,"宮城県":4,"秋田県":5,"山形県":6,"福島県":7,
    "茨城県":8,"栃木県":9,"群馬県":10,"埼玉県":11,"千葉県":12,"東京都":13,"神奈川県":14,
    "新潟県":15,"富山県":16,"石川県":17,"福井県":18,"山梨県":19,"長野県":20,
    "岐阜県":21,"静岡県":22,"愛知県":23,"三重県":24,
    "滋賀県":25,"京都府":26,"大阪府":27,"兵庫県":28,"奈良県":29,"和歌山県":30,
    "鳥取県":31,"島根県":32,"岡山県":33,"広島県":34,"山口県":35,
    "徳島県":36,"香川県":37,"愛媛県":38,"高知県":39,
    "福岡県":40,"佐賀県":41,"長崎県":42,"熊本県":43,"大分県":44,"宮崎県":45,"鹿児島県":46,"沖縄県":47
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_items,only:[:show, :edit, :destroy, :update]
 
  def new
    @item = Item.new
    @item.item_images.build
    @parent = Category.where(id: 1..13)
    @images=@item.item_images.build
  end
  
  def show
    @item=Item.find(params[:id])
    @category = @item.category
    @children = @category.parent
    @Grandparent = @children.parent
    @parentcategory = @category.parent
    @images = @item.item_images
    @image = @images.first
    # @parentcategory = @categorie.parent
  end

    # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:id]}", ancestry: nil).children
  end
    
    # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end
    

  def  done
    # @product_purchaser= Product.find(params[:id])
    # @product_purchaser.update( purchaser_id: current_user.id)
  end

  def buy
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
      # 上記リダイレクト先を修正
    else
      flash.now[:alert] = '必須事項を入力してください。'
      @item = Item.new
      @parent = Category.where(id: 1..13)
      render "new"
    end
  end

  def update
    if @item.update(item_update_params)
       redirect_to root_path controller: :items
    else
      flash[:alert] = '必須事項を入力してください。'
      redirect_to controller: :items, action: :edit
    end
  end

  def destroy
    render :delete unless @item.user_id == current_user.id && @item.destroy
    redirect_to root_path, flash: {alert: '削除しました'}
  end

  private


  def set_items
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item)
            .permit( :name, :text, :category_id, :condition, :brand, :trading_status, :price, :delivery_days, :delivery_area, item_images_attributes: [:image_url]).merge(user_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(
    :name,:image,
    [item_images_attributes: [:image_url, :_destroy, :id]])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_registration-footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", "/"
      %li
        = link_to "メルカリ利用規約", "/"
      %li
        = link_to "特定商取引に関する表記", "/"
  =link_to root_path do
    %img{alt: "mercari", height: "65", src: "logo.png", width: "80"}/
  %p
    %small © 2020 Mercari

app/views/items/_single-header.html.haml
%header.single-header
  %h1
    %a{href: '/'}
      %img{alt: "mercari", src: "logo.png"}

app/views/items/buy.html.haml
.main
  .home-main_header
    .home-main_header_headerInner_mainheader_icon
      = link_to image_tag("logo.png", :size => "185x50")
  .buy-head
    .container
      .titel 購入内容の確認
      .buy-item
        .buy-box
          .imagbox
          .steit  ただの黄色です
      .buy-item2
        .buy_form-a
          .buy_table
            .buy_child 支払い金額
            .buy_cell ¥
        .buy_form-b
          .buy_point
            .buy_checkbox
        .buy_form-c
          %h3.buy_x
            支払い方法
          =link_to "登録してください", class: "buy_z"
        .buy_form-d
          %h3.buy_x
            配送方法
          =link_to "登録してください", class: "buy_z"
        .buy_form-e
          .buy_btn
            = link_to "購入する", class: "buy_submit"
  .home-main_footer_logo2
    = link_to image_tag("logo.png",:size => "90x35"),class:"img"
    .home-main_footer_content_box_d
      =link_to "プライバシーポリシー","#",class: "a"   
    .home-main_footer_content_box_e
      =link_to "FURIMA利用規約","#",class: "a"
    .home-main_footer_content_box_f
      =link_to "特定商取引に関する表記","#",class: "a"
    %p.p＠FURIMA 

app/views/items/edit.html.haml
=render "sell/sell_header"
.main_edit
  %section.main__block
    = form_with model:@item, local:true do |f|
      %h2.sell__block__head
        商品の情報を入力
      .sell__block__form
        .sell__block__form__upload
          %h3.sell__block__form__upload__head
            出品画像
            %span.require 必須
          %p 最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content

              //JSで挿入したhtmlと同じ形 each文でのプレビュー表示
              - @item.item_images.each_with_index do |image, i|
                .preview-box
                  .upper-box
                    = image_tag image.image_url.to_s, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .update-box{"data-image-index": i}
                      %label.edit-btn 編集
                    .delete-box{"data-delete-image-index": i}
                      .delete-btn
                        %span 削除
            .label-content
              //プレビューの数に合わせてforオプションを指定
              = f.label :"image_attributes_#{@item.item_images.length}_image", class: "edit_label-box", id: "label-box--#{@item.item_images.length}" do
                %label{for: "item_images_attributes_#{@item.item_images.length}_image", class: "label-box", id:  "label-box--#{@item.item_images.length}"}
                  %pre.label-box__text-visible クリックしてファイルをアップロード
              .hidden-content
                = f.fields_for :item_images do |i|

                  //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                  = i.file_field :image, class: "hidden-field"
                  = i.check_box:_destroy, class: "hidden-checkbox-#{i.index}"

                  //5つのfile_fieldを準備するに当たって、足りない分を表示
                  - @item.item_images.length.upto(4) do |i|
                    %input{name: "item[item_images_attributes][#{i}][image_url]", id: "item_images_attributes_#{i}_image", class:"hidden-field", type:"file"}
        .sell__block__form__name
          .form-group__name
            %label
              商品名
              %span.require 必須
            %div
              = f.text_field :name, placeholder:"商品名（必須 40文字まで)",class: "form__group__name"
          .tbody
            .tr
              .th 出品者
              .td
                = @item.user.nickname
            .tr
              .th カテゴリー
              .td
                = @item.category.name
            .tr
              .th ブランド
              .td 
                = @item.brand
            .tr
              .th 商品のサイズ
              .td 
            .tr
              .th 商品の状態
              .td 
                = @item.condition
            .tr
              .th 配送料の負担
              .td
                = @item.trading_status
            .tr
              .th 発送元の地域
              .td 
                = @item.delivery_area
            .tr
              .th 発送の目安
              .td
                = @item.delivery_days
        .sell__block__form__btn
          %div
            = f.submit "出品する",class: "btn-default__btn-red"
  = render 'sell/sell_footer'

= javascript_include_tag "edit_item.js"

app/views/items/mihonn.html.haml
商品出品haml

.sell-container
  = render 'single-header'
  %main.sell-main
    %section.sell-main_container
      #sell-container
        %div
          .sell-main_inner
            %h2.sell-main__head 商品の情報を入力
            = form_with model: @product, url: sell_index_path, class:'sell-main__form' do |f|
              .sell-main_upload-box
                %h3.sell-main_upload-head
                  出品画像
                  %span.sell-main__form-require 必須
                %p 最大10枚までアップロードできます
                .sell-main_dropbox-container.clearfix.state-image-number-10
                  .sell-main_upload-items-container
                    .sell-main_upload-items.sell-main_upload-items--have-item-0{ id: 'sell-main__upload-items' }
                      %ul.clearfix{ id: 'output' }
                        = f.label :images, class: 'sell-main__upload-label', id: 'dropArea' do
                          .sell-main_upload-drop-box.sell-main_upload-drop-box--have-item-0{ id: 'sell-main__upload-drop-box' }
                            = f.file_field :images, multiple: true, class: 'sell-main__upload-drop-file', style: 'display: none;'
                            %pre.sell-main_visible-pc
                              ドラッグアンドドロップ
                              またはクリックしてファイルをアップロード
                            %i.fas.fa-camera         
                    = render partial: 'error-messages', locals: { product: @product.errors, column: 'images'}
              .sell-main_content
                .sell-main_form-group
                  = f.label :name do
                    商品名
                    %span.sell-main_form-require 必須
                  %div
                    = f.text_field :name, { class:'sell-main__input-default', placeholder: '商品名（必須 40文字まで)' }
                  = render partial: 'error-messages', locals: {product: f.object, column: 'name'}
                .sell-main_form-group
                  = f.label :description do
                    商品の説明
                    %span.sell-main_form-require 必須
                  = f.text_area :description, { class: 'sell-main__textarea-default', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' }
                  = render partial: 'error-messages', locals: {product: @product, column: ' description'}
              .sell-main_content.clearfix
                %h3.sell-main_sub-head 商品の詳細
                .sell-main_form-box{ id: 'sell-main__form-box--detail' }
                  .sell-main_form-group
                    = f.label :category_id do
                      カテゴリー
                      %span.sell-main_form-require 必須
                    %div{ id: 'sell-main__select-category--wrapper' }
                      .sell-main_select-wrap
                        %i.fas.fa-chevron-down
                        = f.collection_select :category_id, Category.where(sub: '0'), :id, :name, { prompt: '--' }, class: 'sell-main__select-default', id: 'sell-main__select-category--main'
                    =  render partial: 'error-messages', locals: {product: @product, column: ' category_id'}
                  .sell-main__form-group
                    = f.label :condition do
                      商品の状態
                      %span.sell-main_form-require 必須
                    .sell-main_select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :condition_id, Condition.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
                    = render partial: 'error-messages', locals: {product: @product, column: ' condition_id'}
              .sell-main_content.clearfix
                %h3.sell-main_sub-head 配送について
                %a.sell-main_form-question{ href: '#', target: '_blank' }
                  ?
                .sell-main_form-box
                  .sell-main_form-group{ id: 'sell-main__form-group--delivery-charge'}
                    = f.label :delivery_charge_id do
                      配送料の負担
                      %span.sell-main_form-require 必須
                    .sell-main_select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_charge_id, DeliveryCharge.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
                    = render partial: 'error-messages', locals: {product: @product, column: ' delivery_charge_id'}
                  .sell-main_form-group
                    = f.label :delivery_area_id do
                      発送元の地域
                      %span.sell-main_form-require 必須
                    .sell-main_select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :name, { prompt: '--' }, class: 'sell-main__select-default'
                    = render partial: 'error-messages', locals: {product: @product, column: ' prefecture_id'}
                  .sell-main_form-group
                    = f.label :delivery_days do
                      発送までの日数
                      %span.sell-main_form-require 必須
                    .sell-main_select-wrap
                      %i.fas.fa-chevron-down
                      = f.collection_select :delivery_days_id, DeliveryDays.all, :id, :value, { prompt: '--' }, class: 'sell-main__select-default'
                    = render partial: 'error-messages', locals: {product: @product, column: ' delivery_days_id'}
              .sell-main_content.clearfix
                %h3.sell-main_sub-head
                販売価格(300〜9,999,999)
                %a.sell-main_form-question{ href: '#', target: '_blank' }
                  ?
                .sell-main_form-box
                  %ul.sell-main_price
                    %li.sell-main_form-group
                      .clearfix
                        = f.label :price, class: 'sell-main__left' do
                          価格
                          %span.sell-main_form-require 必須
                        .sell-main_right.sell-main_price-input 
                          ¥
                          %div
                            = f.text_field :price, { class: 'sell-main__input-default',id: 'sell-main__price-input', placeholder: '例）300',  value: '' }
                        = render partial: 'error-messages', locals: {product: @product, column: ' price'}
                    %li.clearfix
                      .sell-main_left
                        販売手数料 (10%)
                      .sell-main_right{ id: 'sell-main__fee' } -
                    %li.clearfix.bold
                      .sell-main_left 販売利益
                      .sell-main_right{ id: 'sell-main__profit' } -
              .sell-main_modal{ role: 'dialog', abindex: '-1' }
                .sell-main_modal-inner
              .sell-main_content.sell-main_btn-box
                %div
                  %p
                    = link_to '禁止されている出品', '#', target: '_blank'
                    、
                    = link_to '行為', '#', target: '_blank'
                    を必ずご確認ください。
                  %p
                    またブランド品でシリアルナンバー等がある場合はご記載ください。
                    = link_to '偽ブランドの販売', '#', target: '_blank'
                    は犯罪であり処罰される可能性があります。
                  %p
                    また、出品をもちまして
                    = link_to '加盟店規約', '#'
                    に同意したことになります。
                = f.submit '出品する', class: 'sell-main__btn-default sell-main__btn-red'
                = link_to root_path, class: 'sell-main__btn-default sell-main__btn-gray' do
                  もどる
  = render 'signup/footer'

app/views/items/new.html.haml
.sell-container
  = render 'sell/sell_header'
  .sell-main
    = form_with model: @item, local: true, html: {class:'sell-main__form'}, url: {action: "create"} do |f|
      .main
        .notifications
          - flash.each do |key, value|
            = content_tag(:div, value, class: key)
        %section.main__block
          %h2.sell__block__head
            商品の情報を入力
          .sell__block__form
            .sell__block__form__upload
              %h3.sell__block__form__upload__head
                出品画像
                %span.require 必須
              %p 最大5枚までアップロードできます
              .post__drop__box__container
                .prev-content
                .label-content
                  %label{for: "item_images_attributes_0_image", class: "label-box", id: "label-box--0"}
                    %pre.label-box__text-visible クリックしてファイルをアップロード
                  .hidden-content
                    = f.fields_for :item_images do |i|
                      = i.file_field :image_url, class: "hidden-field",id:"item_images_attributes_0_image"
                      %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][1][image_url]", id: "item_images_attributes_1_image" }
                      %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][2][image_url]", id: "item_images_attributes_2_image" }
                      %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][3][image_url]", id: "item_images_attributes_3_image" }
                      %input{class:"hidden-field", type: "file", name: "item[item_images_attributes][4][image_url]", id: "item_images_attributes_4_image" }
      .sell-main_text
        .sell-main_text_body
          .sell-main_text_body_Family
            .sell-main_text_body_Family_label 商品名
            .sell-main_text_body_Family_span 必須
          = f.text_field :name, { class:'sell-main_text_body_input-default', placeholder: '商品名（必須 40文字まで)' }
          .sell-main_text_body_formerror
        .sell-main_text_style-body
          .sell-main_text_style-body_Family
            .sell-main_text_style-body_Family_label 商品の説明
            .sell-main_text_style-body_Family_span 必須
          = f.text_area :text, { class: 'sell-main_text_style-body_textarea', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' }
          .sell-main_text_style-body_formerror
      .sell-main_categorie
        .sell-main_categorie_title 商品の詳細
        .new__mask__main__right__line
        .new__mask__main__right__form-contents
          .new__mask__main__right__form-contents__title
            .new__mask__main__right__form-contents__title__content 
              カテゴリ
            .new__mask__main__right__form-contents__title__color-content 
              必須
          .listing-select-wrapper
            .listing-select-wrapper__box
            = f.collection_select :category_id, Category.where(id: 1..13, ancestry: nil),:id,:name, {prompt: '選択して下さい'}, {class: 'listing-select-wrapper__box--select', id: 'parent_category',}
            .listing-product-detail__category
              .listing-product-detail__category__2
        .sell-main_categorie_body
          .sell-main_categorie_body_Family
            .sell-main_categorie_body_Family_label ブランド
            .sell-main_categorie_body_Family_span1s 任意
          = f.text_field :brand, { class:'sell-main_text_body_input-default', placeholder: '例）シャネル' }
        .sell-main_categorie_body
          .sell-main_categorie_body_Family
            .sell-main_categorie_body_Family_label 商品の状態
            .sell-main_categorie_body_Family_span 必須
          = f.select :condition, Item.conditions.keys, { prompt: "選択してください"}, {class: 'parent_category'}
      .sell-main_delivery
        .sell-main_delivery_title 配送について
        .sell-main_delivery_body
          .sell-main_delivery_body_Family
            .sell-main_delivery_body_Family_label 配送の負担
            .sell-main_delivery_body_Family_span 必須
          = f.select :trading_status, Item.trading_statuses.keys, { prompt: "選択してください"}, {class: 'parent_category'}
        .sell-main_delivery_body
          .sell-main_delivery_body_Family
            .sell-main_delivery_body_Family_label 配送元の地域
            .sell-main_delivery_body_Family_span 必須
          = f.select :delivery_area, Item.delivery_areas.keys, { prompt: "選択してください"}, {class: 'parent_category'}
          .sell-main_delivery_body_Family
            .sell-main_delivery_body_Family_label 配送までの日数
            .sell-main_delivery_body_Family_span 必須
          = f.select :delivery_days, Item.delivery_days.keys, { prompt: "選択してください"}, {class: 'parent_category'}
      .sell-main_exhibition
        .sell-main_exhibition_title 価格（¥300〜9,999,999)
        .sell-main_delivery_body
          .sell-main_delivery_body_Family
            .sell-main_delivery_body_Family_label 販売価格
            .sell-main_delivery_body_Family_span 必須
          .sell-main_delivery_body_Family_right
            ¥
            = f.text_field :price, id: "pricebox", placeholder: "例） 300" ,class: "parent_category"
      .sell-main_delivery_body_Family_left
        販売手数料 (10%)
        .handling_charge.l-right -
      .sell-main_delivery_body_Family_bold
        販売利益
        .profitFee.l-right -
      .sell-main_delivery_body_Family_btn
        .sell-main_delivery_body_Family_btn_a
          = f.submit "出品する",id: "btn", class: "a"
        .sell-main_delivery_body_Family_btn_b
          =link_to "下書きに保存", "#", class: "a"
        .sell-main_delivery_body_Family_btn_c
          =link_to "戻る", "#", class: "a"
        .sell-content.sell-btn-box
          %div
            %p
              %a{href: "", target: "_blank"} 禁止されている出品
              、
              %a{href: "", target: "_blank"} 行為
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              %a{href: "", target: "_blank"} 偽ブランドの販売
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              %a{href: ""} 加盟店規約
              に同意したことになります。
= render 'sell/sell_footer'

= javascript_include_tag "new_item.js"
= javascript_include_tag "channels/category.js"

app/views/items/show.html.haml
.item-header
  =render "sell/sell_header"
.item-root
  %ul.list
    %li.nav
      = link_to "FURIMA >","#",class:"a"
    %li.nav
      = link_to "メンズ >","#",class:"a"
    %li.nav
      = link_to "ジャケット >","#",class:"a"
    %li.nav
      = link_to "ノーカラージャケット >","#",class:"a"
    %li.nav
      = link_to "product2","#",class:"a"
.item-main
  .item-show
    .content
      .item-box
        .name
          = @item.name
        .body
          %ul.listbox
            - @item.item_images.first(1).each do |image|
              =image_tag image.image_url.to_s,class: "index__main__item__image"
          .lists
            %li.list1
              - @item.item_images.each do |image|
                =image_tag image.image_url.to_s,class: "index__main__item__image"
        .pricebox
          .price
            ¥
            = @item.price
          .tax (税込み)送料込み
        .deta
          .name
            = @item.text
        .table
          -if user_signed_in?
            -if @item.user_id == current_user.id
              .index__main__item__content-item
                = link_to edit_item_path(@item) ,class:"index__main__item__content__option2" do
                  .index__main__item__content__option__edit 商品の編集ページへ
                = link_to "削除する", item_path(@item), method: :delete, class: "index__main__item__content__option"
          .tbody
            .tr
              .th 出品者
              .td
                = @item.user.nickname
            .tr
              .th カテゴリー
              .td
                -if @Grandparent.has_parent?
                -else
                  =link_to "#",class:"index__main__item__content__table__table__tbody__tr__td__a" do
                    =@children.parent.name
                -if @category.has_parent?
                  =link_to "#",class:"index__main__item__content__table__table__tbody__tr__td__a" do
                    =@category.parent.name
                -if @category.has_parent?
                  =link_to "#",class:"index__main__item__content__table__table__tbody__tr__td__a" do
                    =@category.name
            .tr
              .th ブランド
              .td 
                = @item.brand
            .tr
              .th 商品のサイズ
              .td 
            .tr
              .th 商品の状態
              .td 
                = @item.condition
            .tr
              .th 配送料の負担
              .td
                = @item.trading_status
            .tr
              .th 発送元の地域
              .td 
                = @item.delivery_area
            .tr
              .th 発送の目安
              .td
                = @item.delivery_days
        .op
          -if user_signed_in?
            -if @item.user_id == current_user.id
            -else
              .index__main__item__content__commentarea__form__submit__link-Purchase
                = link_to item_purchase_index_path(@item), class: "main-Purchase-btn" do
                  = "購入する"
    .comebox
      .text
      .come 相手のことを考え丁寧なコメントを心がけましょう。
      .btn コメントする
.home-main_banner
  .home-main_banner_inner
    %h2.home-main_banner_inner_title
      だれでもかんたん、、人生を買えるフリマアプリ
    %p.home-main_banner_inner_text
      今すぐ無料ダウンロード！
    .home-main_banner_inner_icon
      %a.a= link_to image_tag("app-store.svg",:size => "180x53")
      %a.a= link_to image_tag("google-play.svg",:size => "180x53")
.item-footer
  =render "sell/sell_footer"